version: "3"

services:
  dev:
    build:
      context: .docker/dev
      dockerfile: Dockerfile
    hostname: dev
    user: node
    volumes:
      - .:/home/node/hostdir
      - workspace-data:/home/node/workspace
    working_dir: /home/node/workspace
    command: sleep infinity

volumes:
  workspace-data:
