version: "3"

services:
  dev:
    build:
      context: .docker/dev
      dockerfile: Dockerfile
    hostname: dev
    user: vscode
    volumes:
      - .:/home/vscode/hostdir
      - workspace-data:/home/vscode/workspace
    working_dir: /home/vscode/workspace
    command: sleep infinity

volumes:
  workspace-data:
